name: Python testing
runs-on: ubuntu-latest
inputs:
  test_type:
    description: Test type [pytest/maven]
    required: true
  extra_arguments:
    description: Extra arguments
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
steps:
- uses: actions/checkout@master
- name: Default argument
  uses: minakoari/actions-test@master
  with:
    args: pytest --help
